'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {AppManagement,OPERATIONS}=require('../src/app-management.cjs');
const {validateHeartbeat}=require('../src/heartbeat.cjs');
const {validateStandingIntent}=require('../src/standing-intents.cjs');
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'app-management-'));const controller={runtime:{status:'ready'},store:{data:{settings:{workspace:root},heartbeat:{},chats:[{status:'running'}],memory:{enabled:true}}},changed(){}};const handlers=new Map();const m=new AppManagement({controller,handlers,filename:path.join(root,'jobs.json')});t.after(()=>{m.close();fs.rmSync(root,{recursive:true,force:true})});return {m,controller,handlers,chat:{id:'chat'}};}
test('heartbeat uses real validation and standing intents are accessible',async t=>{const {m,handlers,chat}=setup(t);handlers.set('saveHeartbeat',p=>validateHeartbeat(p,null,{workspace:process.cwd()}));const result=await m.call('heartbeat_manage',{action:'update',payload:{enabled:true,checklist:'Check once',intervalMinutes:60}},{chat});assert.equal(result.result.enabled,true);await assert.rejects(m.call('heartbeat_manage',{action:'update',payload:{intervalMinutes:0}},{chat}));handlers.set('saveStandingIntent',p=>validateStandingIntent(p));const intent=await m.call('standing_intent_manage',{action:'save',payload:{name:'Done',when:{type:'chat.completed'},action:{type:'automation.run',automationId:'a'}}},{chat});assert.equal(intent.result.name,'Done');});
test('queued operations wait for idle and survive restart; failure is reported',async t=>{const {m,controller,handlers,chat}=setup(t);let calls=0;handlers.set('saveSettings',()=>{calls++;throw Error('bad model')});const result=await m.call('settings_manage',{action:'save',payload:{model:'missing'}},{chat});assert.equal(result.status,'queued');await m.tick();assert.equal(calls,0);m.close();const restored=new AppManagement({controller,handlers,filename:m.filename});t.after(()=>restored.close());controller.store.data.chats[0].status='idle';await restored.tick();assert.equal(calls,1);assert.equal(restored.jobs[0].status,'failed');assert.match(restored.jobs[0].error,/bad model/);});
test('every management action maps to an explicit operation and forbids background mutation',async t=>{const {m}=setup(t);assert.equal(m.specs().length,Object.keys(OPERATIONS).length+1);await assert.rejects(m.call('heartbeat_manage',{action:'update'},{chat:{internal:true}}));await assert.rejects(m.call('heartbeat_manage',{action:'invented'},{chat:{}}));});

test('app overview omits large histories and operation payloads while retaining outcomes',async t=>{const {m,controller,chat}=setup(t);controller.store.data.autonomy={goals:[{id:'g',name:'Goal',status:'idle',history:'x'.repeat(100000)}]};m.jobs=[{id:'op',status:'failed',error:'bad model',payload:{prompt:'x'.repeat(100000)}}];const result=await m.call('app_state',{}, {chat});assert.equal(result.operations[0].error,'bad model');assert.equal(result.goals.items[0].id,'g');assert.ok(JSON.stringify(result).length<5000);assert.ok(result.localTime);});
